### ISSUE TITLE
Incorret schema validation for Object Types

### ISSUE THREAD

**Issue by jhomarolo** [dalssoft/grounds#2]
When using Extended Class Objects schema validation returns an error for all Object fields.
By removing schema validation use case will function normally again

Generic error message:
```
key:"id"
msg:"Key ["id"] does not exist on schema."
type:"invalid value"
```

Request in use case:

`   request: { boleta: Object }`

Lines commented in usecase.js - starting from line 51

```
        if (request) {
            //const requestSchema = schema(this._requestSchema)
            //requestSchema.validate(request)
           // if (!requestSchema.isValid) return Err(requestSchema.errors)
            this._mainStep.context.req = request
        }


```

**Comment by dalssoft** [comment]
when executing your usecase, try run it with a request object with the same schema described.

so, for `request: { boleta: Object }` try `usecase.run({boleta: boleta})`
